# Generated by Django 3.1 on 2021-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgregarProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Preferencia', models.IntegerField(choices=[[0, 'Nike'], [1, 'Gucci'], [2, 'Adidas'], [3, 'Louis Vuitton'], [4, 'Cartier'], [5, 'Zara'], [6, 'H&M']])),
                ('Imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
