# Generated by Django 3.1 on 2021-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20210811_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregarproducto',
            name='Preferencia',
            field=models.IntegerField(choices=[['Nike', 'Nike'], [1, 'Gucci'], [2, 'Adidas'], [3, 'Louis Vuitton'], [4, 'Cartier'], [5, 'Zara'], [6, 'H&M']]),
        ),
    ]
