# Generated by Django 3.2.5 on 2021-08-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Horario', models.DateTimeField()),
            ],
        ),
    ]
